export const privateFeedbackMessages = {
  'zh-CN': {
    privateButton: '私下反馈', publicButton: 'GitHub 公开反馈', title: '向只译提交私下反馈', intro: '反馈会提交到只译的私有接口，不会公开。诊断信息和网页地址均为选填，提交前可查看完整内容。', category: '反馈类型', categories: { performance: '翻译速度', failure: '翻译失败', quality: '翻译质量', compatibility: '网页兼容', suggestion: '功能建议', other: '其他' }, message: '反馈内容', messagePlaceholder: '请描述发生了什么、预期结果，以及是否可以稳定复现。', diagnostics: '附带本地翻译诊断', diagnosticsHint: '默认关闭。仅包含最近的耗时、计数、服务/模型标记和错误类型，不含原文、译文、API Key 或接口地址。', latest: '仅最近一次翻译', last3: '最近 3 次翻译', noDiagnostics: '还没有可用的翻译诊断。', preview: '将提交的诊断信息', pageUrl: '附带网页地址', pageUrlHint: '默认关闭；输入框中的网址会保留查询参数并移除 # 片段，请先检查参数中是否含令牌或个人信息。', pageUrlPlaceholder: 'https://example.com/path', clear: '清除本地诊断', cleared: '本地诊断已清除', submit: '提交反馈', submitting: '提交中…', close: '关闭', required: '请填写反馈内容。', invalidUrl: '网页地址无效，请填写 http 或 https 地址。', success: '提交成功，反馈编号：{id}', failed: '提交失败，请稍后重试。', emptyPreview: '勾选诊断信息后将在这里显示。', browser: '浏览器', version: '扩展版本', optional: '选填', retention: '本地最多保留 5 次翻译诊断，且不超过 24 小时。',
  },
  'en-US': {
    privateButton: 'Private feedback', publicButton: 'Public GitHub issue', title: 'Send private feedback to OnlyTranslate', intro: 'This feedback goes to OnlyTranslate’s private endpoint and is not public. Diagnostics and the page URL are optional, with a full preview before submission.', category: 'Feedback type', categories: { performance: 'Translation speed', failure: 'Translation failure', quality: 'Translation quality', compatibility: 'Page compatibility', suggestion: 'Feature request', other: 'Other' }, message: 'Feedback', messagePlaceholder: 'Describe what happened, what you expected, and whether it reproduces consistently.', diagnostics: 'Include local translation diagnostics', diagnosticsHint: 'Off by default. Includes only timings, counts, service/model markers, and error types—not source text, translations, API keys, or endpoints.', latest: 'Most recent translation', last3: '3 most recent translations', noDiagnostics: 'No translation diagnostics are available yet.', preview: 'Diagnostics to be submitted', pageUrl: 'Include page URL', pageUrlHint: 'Off by default; query parameters are retained and the # fragment is removed. Check parameters for tokens or personal information first.', pageUrlPlaceholder: 'https://example.com/path', clear: 'Clear local diagnostics', cleared: 'Local diagnostics cleared', submit: 'Submit feedback', submitting: 'Submitting…', close: 'Close', required: 'Please enter your feedback.', invalidUrl: 'Enter a valid http or https page URL.', success: 'Submitted. Feedback ID: {id}', failed: 'Submission failed. Please try again later.', emptyPreview: 'Enable diagnostics to preview them here.', browser: 'Browser', version: 'Extension version', optional: 'Optional', retention: 'Up to 5 translation sessions are kept locally for no more than 24 hours.',
  },
  'zh-TW': {
    privateButton: '私下回報', publicButton: 'GitHub 公開回報', title: '向只譯提交私下回報', intro: '回報會送到只譯的私有介面，不會公開。診斷資訊和網頁網址皆為選填，提交前可查看完整內容。', category: '回報類型', categories: { performance: '翻譯速度', failure: '翻譯失敗', quality: '翻譯品質', compatibility: '網頁相容', suggestion: '功能建議', other: '其他' }, message: '回報內容', messagePlaceholder: '請描述發生的情況、預期結果，以及是否能穩定重現。', diagnostics: '附帶本機翻譯診斷', diagnosticsHint: '預設關閉。只包含近期耗時、計數、服務／模型標記和錯誤類型，不含原文、譯文、API Key 或介面網址。', latest: '僅最近一次翻譯', last3: '最近 3 次翻譯', noDiagnostics: '目前沒有可用的翻譯診斷。', preview: '將提交的診斷資訊', pageUrl: '附帶網頁網址', pageUrlHint: '預設關閉；輸入框中的網址會保留查詢參數並移除 # 片段，請先檢查參數中是否含權杖或個人資訊。', pageUrlPlaceholder: 'https://example.com/path', clear: '清除本機診斷', cleared: '本機診斷已清除', submit: '提交回報', submitting: '提交中…', close: '關閉', required: '請填寫回報內容。', invalidUrl: '網頁網址無效，請填寫 http 或 https 網址。', success: '提交成功，回報編號：{id}', failed: '提交失敗，請稍後重試。', emptyPreview: '勾選診斷資訊後會在這裡顯示。', browser: '瀏覽器', version: '擴充功能版本', optional: '選填', retention: '本機最多保留 5 次翻譯診斷，且不超過 24 小時。',
  },
  'ja-JP': {
    privateButton: '非公開フィードバック', publicButton: 'GitHub で公開報告', title: 'OnlyTranslate に非公開で送信', intro: 'フィードバックは OnlyTranslate の非公開エンドポイントへ送信され、公開されません。診断情報とページ URL は任意で、送信前に内容を確認できます。', category: '種類', categories: { performance: '翻訳速度', failure: '翻訳エラー', quality: '翻訳品質', compatibility: 'ページ互換性', suggestion: '機能提案', other: 'その他' }, message: '内容', messagePlaceholder: '発生したこと、期待した結果、再現性を記入してください。', diagnostics: 'ローカル翻訳診断を添付', diagnosticsHint: '既定ではオフです。時間、件数、サービス／モデルの印、エラー種別のみで、原文、訳文、API Key、エンドポイントは含みません。', latest: '直近 1 回の翻訳', last3: '直近 3 回の翻訳', noDiagnostics: '利用できる翻訳診断はまだありません。', preview: '送信する診断情報', pageUrl: 'ページ URL を添付', pageUrlHint: '既定ではオフです。入力欄の URL はクエリを保持し、# フラグメントだけを削除します。トークンや個人情報を含むパラメーターがないか確認してください。', pageUrlPlaceholder: 'https://example.com/path', clear: 'ローカル診断を消去', cleared: 'ローカル診断を消去しました', submit: '送信', submitting: '送信中…', close: '閉じる', required: 'フィードバックを入力してください。', invalidUrl: '有効な http または https URL を入力してください。', success: '送信しました。フィードバック ID：{id}', failed: '送信できませんでした。後でもう一度お試しください。', emptyPreview: '診断情報を有効にすると、ここにプレビューされます。', browser: 'ブラウザー', version: '拡張機能のバージョン', optional: '任意', retention: 'ローカルには最大 5 セッション、24 時間以内の診断だけを保存します。',
  },
} as const
